[package]
name = "rust-order-book"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
rb_tree = "0.5.0"
thiserror = "2.0.15"
uuid = { version = "1.18.0", features = ["v4"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
rand = "0.9.2"

[[bench]]
name = "ob_benchmark"
harness = false
