# Config for cargo-release
# Tag format (e.g. v0.3.0)
tag-name = "v{{version}}"

# Commit messages
pre-release-commit-message = "chore(release): {{version}}"

# Hook: aggiorna CHANGELOG prima del commit/tag
pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}" ]
